### ISSUE TITLE
WCA Competitions in Madrid should appear in green on the calendar

### ISSUE THREAD

**Issue by AlbertoPdRF** [speedcubingmadrid/speedcubingmadrid.org#1]
Color code: #28a745

**Comment by viroulep** [comment]
How do you plan to detect that a competition occurs in Madrid?

If they all come from the same events source, you can just add `color: "#28a745"` in the source:
https://github.com/speedcubingmadrid/speedcubingmadrid.org/blob/abd85bcc7df8ff5131c674a5b3006015b0144f1d/app/webpacker/calendar/index.js#L56

If it depends on the title or attribute of the competition, then you may need to implement fullcalendar's `eventDataTransform`, similarly to what we do on the WCA's competition schedule page:

https://github.com/thewca/worldcubeassociation.org/blob/8ebb8aeb36ce97f51c5e4b857ba2aec53c987ba0/WcaOnRails/app/javascript/show-schedule/index.js#L146-L151

**Comment by AlbertoPdRF** [comment]
The way I currently do it for the home page post is with the `in_madrid` scope: https://github.com/speedcubingmadrid/speedcubingmadrid.org/blob/master/app/models/competition.rb#L10

So I think I'll need something like the WCA's competition schedule page!

**Comment by viroulep** [comment]
I think yes, because the calendar gets the competitions directly from the WCA website!
